### ISSUE TITLE
Some nonsense words allowed

### ISSUE THREAD

**Issue by imacomputa** [stacksmashing/gb-wordle#10]
It allows me to submit certain nonsense words. Sidenote, l can't think of any word this could possibly be:
![Screenshot_20220208-081725](https://user-images.githubusercontent.com/79738715/153008631-d412108e-37e8-4df2-a2da-19476765b127.png)

Further testing, this is practically non-functional as a game. 
![Screenshot_20220208-085320](https://user-images.githubusercontent.com/79738715/153012870-28719205-0c4b-44d8-aa44-9cf78262599d.png)
There's no win state. I got the word and it allowed me to keep guessing ultimately telling me I failed. Also THAMA is not an (English) word. Is this using an English dictionary?

![Screenshot_20220208-084945](https://user-images.githubusercontent.com/79738715/153013229-3e492642-54ae-4136-9ca1-2f2192e185a1.png)
![Screenshot_20220208-084337](https://user-images.githubusercontent.com/79738715/153013234-2a39af7e-8750-4b6b-930c-594e4dc07cae.png)
![Screenshot_20220208-082511](https://user-images.githubusercontent.com/79738715/153013235-d0015389-addf-42c3-8ac7-d5ca9824bb33.png)
It showed RAINK as correct.

**Comment by nezza** [comment]
This is caused by the (bad) bloom filter :) there is a PR that uses the real wordlist though

**Comment by nezza** [comment]
(Also, you didn't get a word: Light gray means the letter is in the wrong position. It's not "unplayable" as others have attested :) )

**Comment by imacomputa** [comment]
Ok, big misunderstanding. Correct letters in the wrong place show up as green on the web version. I figured green meant correct place like the original Wordle. 
Wow, I thought I was losing my mind here. Thanks for the clarification.
